language: node_js
node_js:
  - 10
script:
  - npm run test
  - npm run test:integration
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: app-stone-challenge
  on: master
  run:
    - "npm run migrate"
