version: "3"

services:
  postgresdb:
    image: postgres:11
    ports:
      - "5433:5432"
    restart: always
    networks:
      - stonet
    environment:
      POSTGRES_PASSWORD: root

  stoneapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - stonet
    environment:
      - PORT=8080
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_HOST=postgresdb
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=root
      - DATABASE_STRING=postgres://postgres:root@postgresdb:5432/postgres

networks:
  stonet:
    driver: bridge
